# Default values for central-logging.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

elasticsearch:
  persistence:
    enabled: false

kafka:
  persistence:
    enabled: false